<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>automationtesting</name>
   <tag></tag>
   <elementGuidId>150d8708-550a-4ee1-8425-d45b60614be1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//article[1]//a[.='#automationtesting']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//article[1]//a[.='#automationtesting']</value>
   </webElementProperties>
</WebElementEntity>
