<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title</name>
   <tag></tag>
   <elementGuidId>71950427-f0a3-433e-bc05-bb9bddfed762</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.crayons-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.crayons-title</value>
   </webElementProperties>
</WebElementEntity>
